[package]
name = "poe-minimizer"
version = "0.1.0"
authors = ["Argannor <arga@argannor.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.8", features = ["winuser", "processthreadsapi", "psapi"] }
rev_lines = "0.2.1"
