# Path to your Client.txt, should be inside your Path of Exile Folder -> logs -> Client.txt
# Please note, that back slashes have to be "escaped" meaning you'll have to put them there twice.
log_file_location = "C:\\Program Files (x86)\\Grinding Gear Games\\Path of Exile\\logs\\Client.txt"

# Time in ms to check your Client.txt for your AFK status
log_file_polling_interval_ms = 500

# Depending on your language, the chat will display something like "AFK mode is now ..."
afk_marker = "AFK mode is now"
# Depending on your language, the chat will display somthing like AFK mode is now "ON"
afk_marker_on = "ON"

# Time after which the game gets minimized when tabbing back into the game, while you're still afk.
seconds_until_minimize = 5

# When PoE is currently not running, this tool will periodically check whether PoE has been started in the meantime.
seconds_to_check_for_poe = 30

# The name of your Path of Exile Window - You can find it using the Task Manager. This should be the same for all languages.
window_name = "Path of Exile"
