name: Rust
on: []
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release
    - name: Copy Config
      run: cp Settings.toml target/release/
    - name: Create Zip
      uses: TheDoctor0/zip-release@v0.2.1
      with:
        # Filename for archive
        filename: poe-minimizer-windows-x64.zip
        # Base path for archive files
        path: target/release
        # List of excluded files/directories
        exclusions: ".fingerprint/** build/** deps/** examples/** incremental/** .cargo-lock poe-minimizer.d"
 #   - name: Release
   #   uses: fnkr/github-action-ghr@v1
  #    #if: startsWith(github.ref, 'refs/tags/')
  #    env:
  #      #GHR_COMPRESS: zip
  #      GHR_PATH: poe-minimizer-windows-x64.zip
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
